# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb0abfb516f637ed4d08cc66aa7e572cb3ed5a535dd9d573d3c11e17a47cb1721add165f9ed8845999ceb571da646658fec60f9679bb9038d297a1cb82ba1dcd

test:
  secret_key_base: b89a8b997f2aeb4341740b7a0d39b1fadf5261eea644b0f562242d468758bb77de5386227ea1c449197b4d26b85ec54231b0ff699a81c3518b2f2cb696085875

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
